### ISSUE TITLE
Is get_results deprecated?

### ISSUE THREAD

**Issue by dmark** [auth0/auth0-python#274]
### Describe the problem

Does `get_results` do anything? It doesn't seem to point to a valid mgmt API endpoint.

```
    def get_results(self, job_id):
        """Get results of a job
        Args:
            job_id (str): The id of the job.
        See: https://auth0.com/docs/api/management/v2#!/Jobs/get_results
        """
        url = self._url('%s/results' % job_id)
        return self.client.get(url)
```

The link to the docs doesn't point to anything that actually exists. There's an associated test that point to `jobs/{id}/results` but that endpoint, if it exists, doesn't appear to be documented. For an export job you get the "results URL" from the `get()` call itself. Or is this related to the import job?

**Comment by lbalmaceda** [comment]
Thanks for raising this. It appears that the `/job/{id}/results` endpoint is no longer supported on the API. This was a miss on our side. 

Luckily, the Job status (and results) can be queried using the ["job by id"](https://auth0.com/docs/api/management/v2#!/Jobs/get_jobs_by_id) endpoint which is already exposed on this SDK [here](https://github.com/auth0/auth0-python/blob/master/auth0/v3/management/jobs.py#L32). In the meantime, since this endpoint doesn't work today, I'll mark this method as "deprecated" and re-route the call to the "job by id" method.
