### ISSUE TITLE
Add "all" option to list users

### ISSUE THREAD

**Issue by cancan101** [auth0/auth0-python#45]
Add an `all` option to the users `list` method that handles pulling down all matching users (ie deals with pagination). Right that responsibility seems to be pushed onto the consumer. Further the documentation for how to get total number of pages is sparse.

**Comment by lbalmaceda** [comment]
Hey sorry for the late response! I know this is old but I wanted to reply anyway. `Users` supports pagination since 2015, and until the past month the endpoint was returning the full list of users when called without the pagination params. The thing is that this SDK [enforces them](https://github.com/auth0/auth0-python/commit/c2a94ccff227d198435d452518fb34c477bccae3) when they are missing so there's no workaround unless you create the request yourself. 

We are in the quest of adding pagination support to many of the endpoints since most of them will now enforce it server side. Our next release will have all that. Feel free to open a new issue if you still use this and find anything broken or missing. 

Cheers
