### ISSUE TITLE
User blocks is not instantiated

### ISSUE THREAD

**Issue by mattdodge** [auth0/auth0-python#89]
Unlike the other endpoint classes (e.g., `Users`, `Connections`), the `UserBlocks` class is not instantiated in the root `Auth0` object. Is this by design? Culprit line seems to be here: https://github.com/auth0/auth0-python/blob/master/auth0/v3/management/auth0.py#L43

I would expect to fetch a user's blocks like so
```
auth0.user_blocks.get('auth0|idhere')
```
since I fetch users like this:
```
auth0.users.get('auth0|idhere')
```

But instead I have to pass the domain/token to the `auth0.users_blocks` class myself

**Comment by lbalmaceda** [comment]
Hey @mattdodge. I don't think this was meant this way "by design". It's clear to me in the line you shared that the user blocks entity is being create differently than the rest. To be honest I don't know how one way or the other affects the performance (good/bad way) since I'm not a python dev. But it makes total sense to have all of them being used in the same way.
